version: '3.7'
#
# WaveSnake 2020-03-20
# Docker Compose file for SnakeZig
# This solution are deployed as a Stack Service
# from Portainer
#
services:

  zigbee2mqtt: 
#    image: jagdriver/wavesnake:snakezig
    image: koenkk/zigbee2mqtt:latest
    networks:
      - traefik-public

    extra_hosts:
      - "redis.wavesnake.local:172.16.1.1"
      - "mqt.wavesnake.local:172.16.1.1"
      - "api.wavesnake.local:192.168.1.230"
      - "sql.wavesnake.local:192.168.1.230"
      - "console.wavesnake.local:192.168.1.230"
      - "config.wavesnake.local:192.168.1.230"
      - "sketch.wavesnake.local:192.168.1.230"
      
    volumes:
      - "/mnt/config/snakezig/data:/app/data"
      - "/dev/slzb:/dev/slzb"
    ports:
      # Frontend port
      - 8090:8090

    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.labels.wsnode == sn01
      #
      # we could expose the frontend via Traefik 
      #
networks:
  traefik-public:
    external: true
