version: '3'
#
# Docker Compose file for NodeRed
# This solution are deployed from Portainer
# as a Swarm Stack Service.
#
# OBS! We have to consider Depends on
#
services:
  nodered:
    container_name: nodered
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - ./nodered:/data
    depends_on:
      - homeassistant
      - mosquitto
    environment:
      TZ: "Europe/Copenhagen"
    restart: unless-stopped
 
  
