version: '3.7'
#
# Docker Compose file for SnakeApi
# This solution are deployed as a Stack Service
# from Portainer
#  - /opt/containers/configuration:/opt/containers/configuration


services:
  SnakeApi:
    image: jagdriver/snakeapps:snakeapi
    
    depends_on:
      - mysql
      - redis
    
    container_name: snakeapi
    
    ports:
      - "2000:5000"

    networks:
      traefik-public:

    links:
      - redis

    secrets:
      - SwarmSecret

    volumes:
      - /var/snakelogs/snakeapi:/var/log/snakelogs
      - /var/containers/configuration:/var/containers/configuration
     
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
networks:
  traefik-public:
    external: true

  
secrets:
  SwarmSecret:
    external: true



