#FROM ulsmith/rpi-raspbian-apache-php
FROM httpd:2.4
COPY ./public-html/ /usr/local/apache2/htdocs/

# Remove default apache landing page and copy your files to working directory /var/www/html
# RUN rm /var/www/html/index.html
# ADD ./ /var/www/html

# RUN chmod -R 0755 /var/www/html

#EXPOSE 80
#CMD ["/run.sh"]
