#
# Deploy this service by: docker-compose -f docker-compose-service.yml up -d
#
services:
  mysql:
    container_name: mysql
    image: mysql/mysql-server:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=wavesnake
      - MYSQL_ROOT_HOST=%
    ports:
      - 3306:3306

    networks:
      traefik-public:
        ipv4_address: 10.0.1.20

networks:
  traefik-public:
    external: true