version: '3.7'
#
# Docker Compose file for SnakeEsp
# This solution are deployed from Portainer
# as a Swarm Stack Service.
#
services:
  snakeesp:
    image: jagdriver/snakeapps:snakeesp

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      # - "/var/log/snakelogs/snakeesp:/var/log/snakelogs"
      # - "/mnt/config:/opt/containers"

    networks:
      - traefik-public

    # secrets:
    #     - SwarmSecret

    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.labels.wsnode == sn01
          
      labels:
        - "traefik.enable=true"

        # This section is for snakeesp.wavesnake.local http access
        - "traefik.http.routers.esp-local.entrypoints=web"
        - "traefik.http.routers.esp-local.rule=Host(`snakeesp.wavesnake.local`)"
        - "traefik.http.routers.esp-local.service=esp-local"
        - "traefik.http.services.esp-local.loadbalancer.server.port=80"

        # This section is for console.wavesnake.dk external http redirect
        - "traefik.http.routers.esp-external.entrypoints=web"
        - "traefik.http.routers.esp-external.rule=Host(`snakeesp.wavesnake.dk`)"
        - "traefik.http.routers.esp-external.service=esp-external"
        - "traefik.http.services.esp-external.loadbalancer.server.port=80"
        - "traefik.http.middlewares.esp-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.esp-external.middlewares=esp-https-redirect"

        # This section is for console.wavesnake.dk external https access
        - "traefik.http.routers.esp-secure.entrypoints=secure"
        - "traefik.http.routers.esp-secure.rule=Host(`snakeesp.wavesnake.dk`)"
        - "traefik.http.routers.esp-secure.tls=true"
        - "traefik.http.routers.esp-secure.tls.certresolver=http"
        - "traefik.http.routers.esp-secure.service=esp-secure"
        - "traefik.http.services.esp-secure.loadbalancer.server.port=80"



# secrets:
#   SwarmSecret:
#     external: true

networks:
  traefik-public:
    external: true
