#cloud-config
# vim: syntax=yaml
#

# This file is the !! SWARM MANAGER NODE !! Default Flash config.
# Version: 1.12.3 
# The version are paired with Hypriot OS version 1.12.13.
# You can change the configuration directly in the file or
# run ./flash-config.zsh in the flash directory to be guided
# thru the setup.

# Cloud_Init Documentation: http://cloudinit.readthedocs.io/en/0.7.9/index.html

# TODO: Remove sudo from all commands
# TODO: Docker label must be set
# TODO: Docker port must be set
# TODO: Keep 2.4G radio

# Set your hostname here, the manage_etc_hosts will update the hosts file entries as well
hostname: base01
manage_etc_hosts: false

# You could modify this for your own user information
users:
  - name: manager
    gecos: "Wavesnake Manager"
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: users,docker,video,input
    plain_text_passwd: wavesnake
    lock_passwd: false
    ssh_pwauth: true
    chpasswd: { expire: false }

# # Set the locale of the system
locale: "en_US.UTF-8"

# # Set the timezone
# # Value of 'timezone' must exist in /usr/share/zoneinfo
timezone: "Europe/Copenhagen"